### ISSUE TITLE
StringIndexOutOfBoundsException when executing /sb

### ISSUE THREAD

**Issue by alexcastro1919** [4drian3d/SignedVelocity#103]
Just what title says: StringIndexOutOfBoundsException when executing /sb.

Error: https://hastebin.com/share/zewubipogu.swift

**Comment by alexcastro1919** [comment]
Hastebin link has expired.
`
[18:49:56 ERROR]: Couldn't pass CommandExecuteEvent to signedvelocity 1.2.4-SNAPSHOT
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 2
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
        at io.github._4drian3d.signedvelocity.velocity.listener.PlayerCommandListener.isProxyCommand(PlayerCommandListener.java:123) ~[?:?]
        at io.github._4drian3d.signedvelocity.velocity.listener.PlayerCommandListener.lambda$executeAsync$2(PlayerCommandListener.java:96) ~[?:?]
        at com.velocitypowered.api.event.EventTask$2.execute(EventTask.java:91) ~[PROXY-J-01.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.execute(VelocityEventManager.java:546) ~[PROXY-J-01.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:605) ~[PROXY-J-01.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[PROXY-J-01.jar:3.3.0-SNAPSHOT (git-44b1e0c6-b412)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
`
