### ISSUE TITLE
Couldn't pass CommandExecuteEvent to signedvelocity

### ISSUE THREAD

**Issue by aushot** [4drian3d/SignedVelocity#31]
I have an error for this piece of code:
`commandManager.executeAsync(player,"/tp 20 20 20");`

Error:
`[12:41:48 ERROR]: Couldn't pass CommandExecuteEvent to signedvelocity
java.util.NoSuchElementException: No value present
	at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
	at io.github._4drian3d.signedvelocity.velocity.listener.PlayerCommandListener.lambda$executeAsync$0(PlayerCommandListener.java:40) ~[?:?]
	at com.velocitypowered.api.event.EventTask$2.execute(EventTask.java:91) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.execute(VelocityEventManager.java:545) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:604) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) [?:?]`

**Comment by 4drian3d** [comment]
There is not much I can do, you are trying to execute a command when there is no stable connection from the player to some backend server
