### ISSUE TITLE
Invalid plugin.yml on PaperMC

### ISSUE THREAD

**Issue by PC1up** [4drian3d/SignedVelocity#44]
Hello there,
I am trying to install SignedVelocity on my local network using CloudNet.
The proxy version works just fine, starts without errors and everything, but the PaperMC version always throws this exception:
```
[25.11 18:51:29.588] INFO: [Hub-1] org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[25.11 18:51:29.588] INFO: [Hub-1]      at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[25.11 18:51:29.588] INFO: [Hub-1]      at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[25.11 18:51:29.588] INFO: [Hub-1]      at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-307]
[25.11 18:51:29.588] INFO: [Hub-1]      at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-307]
[25.11 18:51:29.588] INFO: [Hub-1]      at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
[25.11 18:51:29.588] INFO: [Hub-1]      at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
[25.11 18:51:29.588] INFO: [Hub-1]      at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[25.11 18:51:29.588] INFO: [Hub-1] Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
[25.11 18:51:29.588] INFO: [Hub-1]      ... 7 more
```

I am using the latest SignedVelocity version (Paper-1.2.1)
Server Version: 1.19.2
/ver-Output: `This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)`

**Comment by 4drian3d** [comment]
This plugin does not support such old versions
